# Generated by Django 5.1.6 on 2025-02-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0002_alter_group_options_alter_word_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Study activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='words.group')),
                ('study_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='study.studyactivity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studysession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
