# Generated by Django 5.1.6 on 2025-02-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=100)),
                ('romaji', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('parts', models.JSONField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='words', to='words.group')),
            ],
        ),
    ]
