# Generated by Django 5.1.6 on 2025-02-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['japanese']},
        ),
    ]
